import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('ar'), Locale('en'), Locale('fr')];
  static const fallbackLocale = Locale('en');

  static const _ar = <String, String>{
    'appName': 'تامر أكاديمي',
    'site': 'الموقع',
    'enterApp': 'دخول المنصة',
    'enterDashboard': 'دخول لوحة التحكم',
    'tagline': 'تعلّم البرمجة باحتراف — ويب وموبايل',
    'getStarted': 'ابدأ الآن',
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'logout': 'تسجيل الخروج',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'confirmPassword': 'تأكيد كلمة المرور',
    'name': 'الاسم الكامل',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'noAccount': 'ليس لديك حساب؟',
    'haveAccount': 'لديك حساب بالفعل؟',
    'createAccount': 'إنشاء حساب جديد',
    'welcomeBack': 'مرحباً بعودتك!',
    'or': 'أو',
    'welcomeRegister': 'انضم إلينا وابدأ رحلتك التعليمية',
    'loginSubtitle': 'سجّل الدخول للوصول إلى دروسك',
    'registerSubtitle': 'إنشاء حساب مجاني للوصول إلى الدروس المجانية',
    'tracks': 'التخصصات',
    'webDevelopment': 'تطوير الويب',
    'mobileDevelopment': 'تطوير الموبايل',
    'webDescription': 'HTML, CSS, JavaScript ثم الأطر الحديثة مثل React',
    'mobileDescription': 'Flutter و Dart لبناء تطبيقات الأندرويد والويب',
    'moreComingSoon': 'تخصصات أخرى قريباً',
    'comingSoonTracks': 'تخصصات قادمة قريباً',
    'courses': 'الدورات',
    'lessons': 'الدروس',
    'lesson': 'درس',
    'free': 'مجاني',
    'paid': 'مدفوع',
    'locked': 'مقفل',
    'unlocked': 'مفتوح',
    'buyCourse': 'اشترك في الدورة',
    'buyRequest': 'اطلب تفعيل الدورة',
    'purchaseMessage': 'لتفعيل هذه الدورة يرجى التواصل مع الإدارة وسيتم تفعيل حسابك',
    'allLevels': 'كل المستويات',
    'beginner': 'مبتدئ',
    'intermediate': 'متوسط',
    'advanced': 'متقدم',
    'level': 'المستوى',
    'noCourses': 'لا توجد دورات بعد',
    'noLessons': 'لا توجد دروس بعد',
    'markComplete': 'تم إكمال الدرس',
    'completed': 'مكتمل',
    'yourProgress': 'تقدمك',
    'continueLearning': 'تابع التعلم',
    'codeResult': 'نتيجة الكود',
    'code': 'الكود',
    'video': 'الفيديو',
    'watchVideo': 'شاهد الفيديو',
    'exercise': 'التمرين',
    'submitAnswer': 'إرسال الإجابة',
    'correct': 'إجابة صحيحة! 🎉',
    'wrong': 'إجابة خاطئة، حاول مرة أخرى',
    'showSolution': 'عرض الحل',
    'hideSolution': 'إخفاء الحل',
    'solution': 'الحل',
    'answerFirst': 'أجب على السؤال أولاً لعرض الحل',
    'writeSolutionHere': 'اكتب حلك هنا...',
    'exerciseHint': '💡 استند إلى ما تعلمته في الدروس السابقة',
    'answerSubmitted': 'تم إرسال إجابتك ✓',
    'tryAgain': 'حاول مرة أخرى',
    'nextLesson': 'الدرس التالي',
    'previousLesson': 'الدرس السابق',
    'home': 'الرئيسية',
    'myCourses': 'دوراتي',
    'profile': 'حسابي',
    'loginFirst': 'سجّل الدخول أولاً للوصول إلى هذه الصفحة',
    'admin': 'لوحة التحكم',
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'theme': 'المظهر',
    'darkMode': 'الوضع الليلي',
    'lightMode': 'الوضع الفاتح',
    'arabic': 'العربية',
    'english': 'الإنجليزية',
    'french': 'الفرنسية',
    'adminPanel': 'لوحة التحكم',
    'manageCourses': 'إدارة الدورات',
    'manageLessons': 'إدارة الدروس',
    'manageUsers': 'إدارة المستخدمين',
    'manageRequests': 'طلبات الوصول',
    'requestAccess': 'طلب الوصول',
    'requestSent': 'تم إرسال الطلب بنجاح',
    'requestPending': 'طلبك قيد المراجعة',
    'requestPendingHint': 'سيتم مراجعة طلبك من قبل الإدارة قريباً',
    'requestDenied': 'تم رفض الطلب',
    'requestDeniedHint': 'يمكنك إعادة إرسال الطلب',
    'pendingReview': 'قيد المراجعة',
    'resendRequest': 'إعادة إرسال الطلب',
    'noRequests': 'لا توجد طلبات',
    'approve': 'قبول',
    'deny': 'رفض',
    'approved': 'مقبول',
    'denied': 'مرفوض',
    'pending': 'قيد الانتظار',
    'availableCourses': 'الدورات المتاحة',
    'markIncomplete': 'إلغاء الإكمال',
    'codeTypeHtml': 'HTML / CSS / JS',
    'codeTypeDart': 'Dart / Flutter',
    'preview': 'معاينة',
    'noPreview': 'لا يوجد كود لعرضه',
    'noContent': 'لا يوجد محتوى لهذا الدرس',
    'showingFallbackLang': 'يُعرض بلغة أخرى لعدم توفره بلغتك',
    'addCourse': 'إضافة دورة',
    'editCourse': 'تعديل دورة',
    'addLesson': 'إضافة درس',
    'editLesson': 'تعديل درس',
    'delete': 'حذف',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'edit': 'تعديل',
    'editUser': 'تعديل المستخدم',
    'deleteUser': 'حذف المستخدم',
    'deleteUserConfirm': 'هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
    'cannotDeleteSelf': 'لا يمكنك حذف حسابك الخاص',
    'userDeleted': 'تم حذف المستخدم',
    'title': 'العنوان',
    'description': 'الوصف',
    'content': 'المحتوى',
    'track': 'التخصص',
    'price': 'السعر',
    'order': 'الترتيب',
    'published': 'منشور',
    'videoUrl': 'رابط الفيديو (يوتيوب أو درايف)',
    'codeHtml': 'كود HTML/CSS/JS',
    'codeDart': 'كود Dart/Flutter',
    'hasExercise': 'يوجد تمرين',
    'question': 'السؤال',
    'options': 'الخيارات',
    'answerIndex': 'رقم الإجابة الصحيحة',
    'userRole': 'الدور',
    'accessCourses': 'الدورات المفعّلة',
    'student': 'طالب',
    'adminRole': 'مدير',
    'search': 'بحث...',
    'deleteConfirm': 'هل أنت متأكد من الحذف؟',
    'deleteWarning': 'لا يمكن التراجع عن هذا الإجراء',
    'deleteLessonWarning': 'سيتم حذف الدرس نهائياً',
    'welcome': 'مرحباً',
    'members': 'طلاب',
    'openCourses': 'دورات مفتوحة',
    'statsCourses': 'دورات',
    'statsLessons': 'دروس',
    'statsUsers': 'مستخدمين',
    'lessonContent': 'محتوى الدرس',
    'adminOnly': 'منطقة المدير',
    'switchToStudent': 'العودة لحساب الطالب',
    'users': 'المستخدمين',
    'noAccess': 'لا تملك صلاحية الوصول لهذه الدورة',
    'noAccessHint': 'هذه دورة مدفوعة، تواصل مع الإدارة لتفعيلها',
    'contactAdmin': 'تواصل مع الإدارة',
    'adminContact': 'لتفعيل الدورة، أرسل بريداً إلى الإدارة',
    'emailSent': 'تم إرسال رابط إعادة التعيين إلى بريدك',
    'resetPassword': 'إعادة تعيين كلمة المرور',
    'sendResetLink': 'إرسال الرابط',
    'invalidEmail': 'بريد إلكتروني غير صالح',
    'weakPassword': 'كلمة المرور ضعيفة (6 أحرف على الأقل)',
    'emailInUse': 'البريد مستخدم بالفعل',
    'userNotFound': 'لا يوجد حساب بهذا البريد',
    'wrongPassword': 'كلمة المرور غير صحيحة',
    'unknownError': 'حدث خطأ، حاول مرة أخرى',
    'passwordsDontMatch': 'كلمتا المرور غير متطابقتين',
    'loginSuccess': 'تم تسجيل الدخول بنجاح',
    'registerSuccess': 'تم إنشاء الحساب بنجاح',
    'loading': 'جاري التحميل...',
    'retry': 'إعادة المحاولة',
    'error': 'خطأ',
    'success': 'نجاح',
    'saved': 'تم الحفظ بنجاح',
    'deleted': 'تم الحذف بنجاح',
    'notFound': 'غير موجود',
    'lessonProgress': 'اكتملت جميع الدروس في هذه الدورة!',
    'startCourse': 'ابدأ الدورة',
    'backToCourses': 'العودة إلى الدورات',
    'exercisesSolved': 'تمارين محلولة',
    'totalProgress': 'التقدم العام',
    'learningTracks': 'المسارات التعليمية',
    'featuredCourses': 'الدورات المتاحة',
    'whyUs': 'لماذا تامر أكاديمي؟',
    'whyUs1Title': 'دروس عملية',
    'whyUs1Desc': 'تتعلم بالكود وتشاهد النتيجة مباشرة أمامك',
    'whyUs2Title': 'مستويات متعددة',
    'whyUs2Desc': 'محتوى يناسب المبتدئ والمتقدم',
    'whyUs3Title': '3 لغات',
    'whyUs3Desc': 'عربي، إنجليزي وفرنسي',
    'joinToday': 'انضم اليوم وابدأ رحلتك',
    'heroTitle': 'أطلق العنان لمستقبلك في البرمجة',
    'heroSubtitle': 'دورات تفاعلية في تطوير الويب والموبايل مع كود مباشر ونتائج فورية',
    'learnMore': 'اكتشف المزيد',
    'privacy': 'الخصوصية',
    'terms': 'الشروط',
    'rights': 'جميع الحقوق محفوظة',
    'codeNote': 'نصيحة: جرّب تعديل الكود ثم أعد التحميل لترى النتيجة بنفسك',
    'runCode': 'تشغيل الكود',
    'refreshResult': 'تحديث النتيجة',
    'fullscreen': 'ملء الشاشة',
    'openInNewTab': 'فتح في نافذة جديدة',
    'dartpadNote': 'هذا الدرس يستخدم DartPad — قد يستغرق التحميل لحظات',
    'viewCode': 'عرض الكود',
    'viewResult': 'عرض النتيجة',
    'tabs': 'الأقسام',
    'videoNote': 'رابط الفيديو: يوتيوب أو درايف',
    'homeSubtitle': 'تعلم البرمجة بأسلوب احترافي — ويب وموبايل',
    'webDevHeroTitle': 'تطوير المواقع\nبأسهل الطرق',
    'webDevHeroSubtitle': 'HTML, CSS, JavaScript وأحدث الأطر مثل React',
    'mobileDevHeroTitle': 'تطبيقات الموبايل\nبـ Flutter',
    'mobileDevHeroSubtitle': 'بناء تطبيقات Android وiOS وويب بلغة Dart',
    'trustedBy': 'يستخدمه الطلاب في',
    'featureShowcaseTitle': 'تجربة تعلم\nلا مثيل لها',
    'featureShowcaseSubtitle': 'دورات تفاعلية مع كود مباشر ونتائج فورية — تعلم بالتطبيق لا بالحفظ',
    'feature1': 'فيديوهات تعليمية بجودة عالية',
    'feature2': 'كود تفاعلي مع معاينة مباشرة',
    'feature3': 'تطبيق على الهاتف والويب',
    'feature4': 'تمارين تفاعلية مع تصحيح فوري',
    'addTrack': 'إضافة تخصص',
    'editTrack': 'تعديل تخصص',
    'noTracks': 'لا توجد تخصصات بعد',
    'tags': 'الكلمات المفتاحية',
    'color': 'اللون',
    'icon': 'الأيقونة',
    'pickImage': 'اضغط لاختيار صورة',
    'draft': 'مسودة',
    'image': 'الصورة',
    'imageUrlHint': 'الصق رابط الصورة هنا...',
    'pickFromGallery': 'اختيار من المعرض',
    'pickFromCamera': 'التقاط بالكاميرا',
    'pickImageOrUrl': 'اختر صورة أو أدخل رابط',
    'invalidImageUrl': 'رابط الصورة غير صالح',
    'imagePickError': 'حدث خطأ أثناء اختيار الصورة',
    'browseFiles': 'استعراض الملفات',
    'dragToResize': 'اسحب لتغيير الحجم — أو حدده بالأرقام أدناه',
    'imageDimensions': 'أبعاد الصورة',
    'reset': 'إعادة تعيين',
    'width': 'العرض',
    'height': 'الارتفاع',
    'auto': 'تلقائي',
    'imageFit': 'طريقة العرض',
    'fitCover': 'تغطية (قص)',
    'fitContain': 'احتواء (كاملة)',
    'fitFill': 'تمديد',
    'fitWidth': 'بعرض الحاوية',
    'storagePermissionError': 'صلاحية التخزين مرفوضة — تأكد من قواعد Storage وأن حسابك admin',
    'imageUploadFailed': 'فشل رفع الصورة، سيتم الحفظ بالرابط إن وجد',
    // ── Homework & Questions ──
    'homework': 'الواجب المنزلي',
    'homeworkHint': 'اكتب حلك هنا بالكود ثم أرسله للمراجعة',
    'writeCodeHere': 'اكتب الكود هنا...',
    'submitHomework': 'إرسال الواجب',
    'homeworkSent': 'تم إرسال الواجب بنجاح ✓',
    'homeworkPending': 'قيد المراجعة',
    'homeworkReviewed': 'تمت المراجعة',
    'homeworkEmptyError': 'لا يمكن إرسال واجب فارغ',
    'myHomeworks': 'واجباتي',
    'noHomeworks': 'لا توجد واجبات بعد',
    'grade': 'الدرجة',
    'feedback': 'ملاحظة المدرس',
    'noFeedback': 'لا توجد ملاحظة',
    'randomQuestion': 'سؤال عشوائي',
    'pickRandom': 'اختر سؤالاً عشوائياً',
    'questionNumber': 'السؤال رقم',
    'allowRepeat': 'السماح بالتكرار',
    'noRepeat': 'بدون تكرار',
    'seenQuestions': 'الأسئلة التي ظهرت',
    'resetSeen': 'إعادة تعيين السجل',
    'allQuestionsSeen': 'تم عرض جميع الأسئلة! اضغط إعادة تعيين',
    'allQuestions': 'كل الأسئلة',
    'importExcel': 'استيراد من Excel',
    'pasteQuick': 'لصق سريع',
    'need9Questions': 'يجب إدخال 9 أسئلة (3 لغات إلزامية)',
    'questionsCount': 'عدد الأسئلة',
    'homeworkSubmissions': 'تسليمات الواجبات',
    'noSubmissions': 'لا توجد تسليمات بعد',
    'review': 'مراجعة',
    'reviewHomework': 'مراجعة الواجب',
    'homeworkReviewSuccess': 'تمت المراجعة بنجاح',
    'pendingHomeworks': 'واجبات معلقة',
    'reviewedHomeworks': 'تمت مراجعتها',
    'shuffleQuestions': 'خلط الأسئلة',
    'homeworkPrompt': 'نص الواجب',
    'hasHomework': 'يوجد واجب منزلي',
    'questions': 'الأسئلة',
    'oralQuestions': 'أسئلة شفوية',
    'homeworkCode': 'كود الواجب',
    'codeAnswer': 'إجابة الكود',
    'quickPasteTitle': 'لصق سريع — كل سؤال في سطر',
    'quickPasteHint': 'الصق الأسئلة هنا، سطر لكل سؤال',
    'quickPasteSolutionsHint': 'الصق الحلول هنا، سطر لكل حل',
    'importHint': 'Excel أعمدة: q_ar | s_ar | q_en | s_en | q_fr | s_fr',
    'homeworkProgress': 'تقدم الواجبات',
    'filterByCourse': 'فلترة بالدورة',
    'filterByStatus': 'فلترة بالحالة',
    'allStatus': 'كل الحالات',
    'newHomeworksBadge': 'جديد',
  };

  static const _en = <String, String>{
    'appName': 'Tamer Academy',
    'tagline': 'Learn programming professionally — Web & Mobile',
    'getStarted': 'Get Started',
    'site': 'Site',
    'enterApp': 'Enter platform',
    'enterDashboard': 'Admin dashboard',
    'login': 'Login',
    'register': 'Sign Up',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'name': 'Full Name',
    'forgotPassword': 'Forgot password?',
    'noAccount': 'Don\'t have an account?',
    'haveAccount': 'Already have an account?',
    'createAccount': 'Create Account',
    'welcomeBack': 'Welcome back!',
    'or': 'or',
    'welcomeRegister': 'Join us and start your learning journey',
    'loginSubtitle': 'Log in to access your lessons',
    'registerSubtitle': 'Create a free account to access free lessons',
    'tracks': 'Tracks',
    'webDevelopment': 'Web Development',
    'mobileDevelopment': 'Mobile Development',
    'webDescription': 'HTML, CSS, JavaScript then modern frameworks like React',
    'mobileDescription': 'Flutter and Dart to build Android and web apps',
    'moreComingSoon': 'More tracks coming soon',
    'comingSoonTracks': 'More tracks coming soon',
    'courses': 'Courses',
    'lessons': 'Lessons',
    'lesson': 'Lesson',
    'free': 'Free',
    'paid': 'Paid',
    'locked': 'Locked',
    'unlocked': 'Unlocked',
    'buyCourse': 'Subscribe to Course',
    'buyRequest': 'Request Course Activation',
    'purchaseMessage': 'To activate this course, please contact the admin and your account will be activated',
    'allLevels': 'All levels',
    'beginner': 'Beginner',
    'intermediate': 'Intermediate',
    'advanced': 'Advanced',
    'level': 'Level',
    'noCourses': 'No courses yet',
    'noLessons': 'No lessons yet',
    'markComplete': 'Mark as Completed',
    'completed': 'Completed',
    'yourProgress': 'Your Progress',
    'continueLearning': 'Continue Learning',
    'codeResult': 'Code Result',
    'code': 'Code',
    'video': 'Video',
    'watchVideo': 'Watch Video',
    'exercise': 'Exercise',
    'submitAnswer': 'Submit Answer',
    'correct': 'Correct answer! 🎉',
    'wrong': 'Wrong answer, try again',
    'showSolution': 'Show Solution',
    'hideSolution': 'Hide Solution',
    'solution': 'Solution',
    'answerFirst': 'Answer the question first to see the solution',
    'writeSolutionHere': 'Write your solution here...',
    'exerciseHint': '💡 Based on what you learned in previous lessons',
    'answerSubmitted': 'Answer submitted ✓',
    'tryAgain': 'Try Again',
    'nextLesson': 'Next Lesson',
    'previousLesson': 'Previous Lesson',
    'home': 'Home',
    'myCourses': 'My Courses',
    'profile': 'Profile',
    'loginFirst': 'Please log in first to access this page',
    'admin': 'Admin Panel',
    'settings': 'Settings',
    'language': 'Language',
    'theme': 'Theme',
    'darkMode': 'Dark Mode',
    'lightMode': 'Light Mode',
    'arabic': 'Arabic',
    'english': 'English',
    'french': 'French',
    'adminPanel': 'Admin Panel',
    'manageCourses': 'Manage Courses',
    'manageLessons': 'Manage Lessons',
    'manageUsers': 'Manage Users',
    'manageRequests': 'Access Requests',
    'requestAccess': 'Request Access',
    'requestSent': 'Request sent successfully',
    'requestPending': 'Your request is pending',
    'requestPendingHint': 'Your request will be reviewed soon',
    'requestDenied': 'Request denied',
    'requestDeniedHint': 'You can resend the request',
    'pendingReview': 'Under review',
    'resendRequest': 'Resend request',
    'noRequests': 'No requests',
    'approve': 'Approve',
    'deny': 'Deny',
    'approved': 'Approved',
    'denied': 'Denied',
    'pending': 'Pending',
    'availableCourses': 'Available Courses',
    'markIncomplete': 'Mark as Incomplete',
    'codeTypeHtml': 'HTML / CSS / JS',
    'codeTypeDart': 'Dart / Flutter',
    'preview': 'Preview',
    'noPreview': 'No code to preview',
    'noContent': 'No content for this lesson',
    'showingFallbackLang': 'Showing in another language',
    'addCourse': 'Add Course',
    'editCourse': 'Edit Course',
    'addLesson': 'Add Lesson',
    'editLesson': 'Edit Lesson',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'editUser': 'Edit User',
    'deleteUser': 'Delete User',
    'deleteUserConfirm': 'Are you sure you want to delete this user? This action cannot be undone.',
    'cannotDeleteSelf': 'You cannot delete your own account',
    'userDeleted': 'User deleted',
    'title': 'Title',
    'description': 'Description',
    'content': 'Content',
    'track': 'Track',
    'price': 'Price',
    'order': 'Order',
    'published': 'Published',
    'videoUrl': 'Video URL (YouTube or Drive)',
    'codeHtml': 'HTML/CSS/JS Code',
    'codeDart': 'Dart/Flutter Code',
    'hasExercise': 'Has Exercise',
    'question': 'Question',
    'options': 'Options',
    'answerIndex': 'Correct Answer Index',
    'userRole': 'Role',
    'accessCourses': 'Activated Courses',
    'student': 'Student',
    'adminRole': 'Admin',
    'search': 'Search...',
    'deleteConfirm': 'Are you sure you want to delete?',
    'deleteWarning': 'This action cannot be undone',
    'deleteLessonWarning': 'The lesson will be permanently deleted',
    'welcome': 'Welcome',
    'members': 'Students',
    'openCourses': 'Open Courses',
    'statsCourses': 'Courses',
    'statsLessons': 'Lessons',
    'statsUsers': 'Users',
    'lessonContent': 'Lesson Content',
    'adminOnly': 'Admin Area',
    'switchToStudent': 'Back to Student View',
    'users': 'Users',
    'noAccess': 'You don\'t have access to this course',
    'noAccessHint': 'This is a paid course, contact the admin to activate it',
    'contactAdmin': 'Contact Admin',
    'adminContact': 'To activate the course, send an email to the admin',
    'emailSent': 'Reset link sent to your email',
    'resetPassword': 'Reset Password',
    'sendResetLink': 'Send Reset Link',
    'invalidEmail': 'Invalid email',
    'weakPassword': 'Password too weak (min 6 characters)',
    'emailInUse': 'Email already in use',
    'userNotFound': 'No account with this email',
    'wrongPassword': 'Incorrect password',
    'unknownError': 'Something went wrong, try again',
    'passwordsDontMatch': 'Passwords do not match',
    'loginSuccess': 'Logged in successfully',
    'registerSuccess': 'Account created successfully',
    'loading': 'Loading...',
    'retry': 'Retry',
    'error': 'Error',
    'success': 'Success',
    'saved': 'Saved successfully',
    'deleted': 'Deleted successfully',
    'notFound': 'Not found',
    'lessonProgress': 'All lessons in this course completed!',
    'startCourse': 'Start Course',
    'backToCourses': 'Back to Courses',
    'exercisesSolved': 'Exercises Solved',
    'totalProgress': 'Overall Progress',
    'learningTracks': 'Learning Tracks',
    'featuredCourses': 'Available Courses',
    'whyUs': 'Why Tamer Academy?',
    'whyUs1Title': 'Hands-on Lessons',
    'whyUs1Desc': 'Learn with code and see the result instantly',
    'whyUs2Title': 'Multiple Levels',
    'whyUs2Desc': 'Content for beginners and advanced learners',
    'whyUs3Title': '3 Languages',
    'whyUs3Desc': 'Arabic, English and French',
    'joinToday': 'Join today and start your journey',
    'heroTitle': 'Unlock your future in programming',
    'heroSubtitle': 'Interactive courses in web & mobile development with live code and instant results',
    'learnMore': 'Learn More',
    'privacy': 'Privacy',
    'terms': 'Terms',
    'rights': 'All rights reserved',
    'codeNote': 'Tip: try modifying the code then reload to see the result yourself',
    'runCode': 'Run Code',
    'refreshResult': 'Refresh Result',
    'fullscreen': 'Fullscreen',
    'openInNewTab': 'Open in New Tab',
    'dartpadNote': 'This lesson uses DartPad — loading may take a moment',
    'viewCode': 'View Code',
    'viewResult': 'View Result',
    'tabs': 'Sections',
    'videoNote': 'Video link: YouTube or Drive',
    'homeSubtitle': 'Learn programming professionally — Web & Mobile',
    'webDevHeroTitle': 'Web Development\nMade Easy',
    'webDevHeroSubtitle': 'HTML, CSS, JavaScript and modern frameworks like React',
    'mobileDevHeroTitle': 'Mobile Apps\nwith Flutter',
    'mobileDevHeroSubtitle': 'Build Android, iOS and web apps with Dart',
    'trustedBy': 'Trusted by students in',
    'featureShowcaseTitle': 'A Learning\nExperience Like No Other',
    'featureShowcaseSubtitle': 'Interactive courses with live code and instant results — learn by doing, not memorizing',
    'feature1': 'High-quality video tutorials',
    'feature2': 'Interactive code with live preview',
    'feature3': 'Available on mobile and web',
    'feature4': 'Interactive exercises with instant feedback',
    'addTrack': 'Add Track',
    'editTrack': 'Edit Track',
    'noTracks': 'No tracks yet',
    'tags': 'Tags',
    'color': 'Color',
    'icon': 'Icon',
    'pickImage': 'Tap to pick an image',
    'draft': 'Draft',
    'image': 'Image',
    'imageUrlHint': 'Paste image URL here...',
    'pickFromGallery': 'Pick from Gallery',
    'pickFromCamera': 'Take Photo',
    'pickImageOrUrl': 'Choose an image or enter a URL',
    'invalidImageUrl': 'Invalid image URL',
    'imagePickError': 'Error picking image',
    'browseFiles': 'Browse Files',
    'dragToResize': 'Drag to resize — or enter values below',
    'imageDimensions': 'Image Dimensions',
    'reset': 'Reset',
    'width': 'Width',
    'height': 'Height',
    'auto': 'Auto',
    'imageFit': 'Fit Mode',
    'fitCover': 'Cover (crop)',
    'fitContain': 'Contain (full)',
    'fitFill': 'Stretch',
    'fitWidth': 'Fit Width',
    'storagePermissionError': 'Storage permission denied — check Storage rules and admin role',
    'imageUploadFailed': 'Image upload failed, saving with URL if provided',
    'homework': 'Homework',
    'homeworkHint': 'Write your code here then submit for review',
    'writeCodeHere': 'Write code here...',
    'submitHomework': 'Submit Homework',
    'homeworkSent': 'Homework submitted ✓',
    'homeworkPending': 'Pending review',
    'homeworkReviewed': 'Reviewed',
    'homeworkEmptyError': 'Cannot submit empty homework',
    'myHomeworks': 'My Homeworks',
    'noHomeworks': 'No homeworks yet',
    'grade': 'Grade',
    'feedback': 'Teacher feedback',
    'noFeedback': 'No feedback',
    'randomQuestion': 'Random Question',
    'pickRandom': 'Pick random question',
    'questionNumber': 'Question #',
    'allowRepeat': 'Allow repeat',
    'noRepeat': 'No repeat',
    'seenQuestions': 'Seen questions',
    'resetSeen': 'Reset history',
    'allQuestionsSeen': 'All questions seen! Tap reset',
    'allQuestions': 'All Questions',
    'importExcel': 'Import Excel',
    'pasteQuick': 'Quick Paste',
    'need9Questions': 'Must enter 9 questions (3 langs required)',
    'questionsCount': 'Questions count',
    'homeworkSubmissions': 'Homework Submissions',
    'noSubmissions': 'No submissions yet',
    'review': 'Review',
    'reviewHomework': 'Review Homework',
    'homeworkReviewSuccess': 'Reviewed successfully',
    'pendingHomeworks': 'Pending',
    'reviewedHomeworks': 'Reviewed',
    'shuffleQuestions': 'Shuffle',
    'homeworkPrompt': 'Homework prompt',
    'hasHomework': 'Has homework',
    'questions': 'Questions',
    'oralQuestions': 'Oral Questions',
    'homeworkCode': 'Homework Code',
    'codeAnswer': 'Code Answer',
    'quickPasteTitle': 'Quick paste — one per line',
    'quickPasteHint': 'Paste questions, one per line',
    'quickPasteSolutionsHint': 'Paste solutions, one per line',
    'importHint': 'Excel cols: q_ar | s_ar | q_en | s_en | q_fr | s_fr',
    'homeworkProgress': 'Homework Progress',
    'filterByCourse': 'Filter by course',
    'filterByStatus': 'Filter by status',
    'allStatus': 'All statuses',
    'newHomeworksBadge': 'New',
  };

  static const _fr = <String, String>{
    'appName': 'Tamer Academy',
    'tagline': 'Apprenez la programmation professionnellement — Web & Mobile',
    'getStarted': 'Commencer',
    'site': 'Site',
    'enterApp': 'Entrer sur la plateforme',
    'enterDashboard': 'Tableau de bord admin',
    'login': 'Connexion',
    'register': 'S\'inscrire',
    'logout': 'Déconnexion',
    'email': 'E-mail',
    'password': 'Mot de passe',
    'confirmPassword': 'Confirmer le mot de passe',
    'name': 'Nom complet',
    'forgotPassword': 'Mot de passe oublié?',
    'noAccount': 'Pas de compte?',
    'haveAccount': 'Déjà un compte?',
    'createAccount': 'Créer un compte',
    'welcomeBack': 'Bon retour!',
    'or': 'ou',
    'welcomeRegister': 'Rejoignez-nous et commencez votre parcours',
    'loginSubtitle': 'Connectez-vous pour accéder à vos leçons',
    'registerSubtitle': 'Créez un compte gratuit pour accéder aux leçons gratuites',
    'tracks': 'Filières',
    'webDevelopment': 'Développement Web',
    'mobileDevelopment': 'Développement Mobile',
    'webDescription': 'HTML, CSS, JavaScript puis les frameworks modernes comme React',
    'mobileDescription': 'Flutter et Dart pour créer des applications Android et web',
    'moreComingSoon': 'Plus de filières bientôt',
    'comingSoonTracks': 'Plus de filières bientôt',
    'courses': 'Cours',
    'lessons': 'Leçons',
    'lesson': 'Leçon',
    'free': 'Gratuit',
    'paid': 'Payant',
    'locked': 'Verrouillé',
    'unlocked': 'Déverrouillé',
    'buyCourse': "S'abonner au cours",
    'buyRequest': "Demander l'activation du cours",
    'purchaseMessage': 'Pour activer ce cours, contactez l\'administration et votre compte sera activé',
    'allLevels': 'Tous les niveaux',
    'beginner': 'Débutant',
    'intermediate': 'Intermédiaire',
    'advanced': 'Avancé',
    'level': 'Niveau',
    'noCourses': 'Pas encore de cours',
    'noLessons': 'Pas encore de leçons',
    'markComplete': 'Marquer comme terminé',
    'completed': 'Terminé',
    'yourProgress': 'Votre progression',
    'continueLearning': 'Continuer',
    'codeResult': 'Résultat du code',
    'code': 'Code',
    'video': 'Vidéo',
    'watchVideo': 'Regarder la vidéo',
    'exercise': 'Exercice',
    'submitAnswer': 'Envoyer la réponse',
    'correct': 'Bonne réponse! 🎉',
    'wrong': 'Mauvaise réponse, réessayez',
    'showSolution': 'Voir la solution',
    'hideSolution': 'Masquer la solution',
    'solution': 'Solution',
    'answerFirst': 'Répondez d\'abord à la question pour voir la solution',
    'writeSolutionHere': 'Écrivez votre solution ici...',
    'exerciseHint': '💡 Basé sur les leçons précédentes',
    'answerSubmitted': 'Réponse envoyée ✓',
    'tryAgain': 'Réessayer',
    'nextLesson': 'Leçon suivante',
    'previousLesson': 'Leçon précédente',
    'home': 'Accueil',
    'myCourses': 'Mes cours',
    'profile': 'Profil',
    'loginFirst': 'Veuillez vous connecter d’abord pour accéder à cette page',
    'admin': 'Panneau admin',
    'settings': 'Paramètres',
    'language': 'Langue',
    'theme': 'Thème',
    'darkMode': 'Mode sombre',
    'lightMode': 'Mode clair',
    'arabic': 'Arabe',
    'english': 'Anglais',
    'french': 'Français',
    'adminPanel': 'Panneau d\'administration',
    'manageCourses': 'Gérer les cours',
    'manageLessons': 'Gérer les leçons',
    'manageUsers': 'Gérer les utilisateurs',
    'manageRequests': 'Demandes d\'accès',
    'requestAccess': 'Demander l\'accès',
    'requestSent': 'Demande envoyée avec succès',
    'requestPending': 'Votre demande est en attente',
    'requestPendingHint': 'Votre demande sera examinée bientôt',
    'requestDenied': 'Demande refusée',
    'requestDeniedHint': 'Vous pouvez renvoyer la demande',
    'pendingReview': 'En cours d\'examen',
    'resendRequest': 'Renvoyer la demande',
    'noRequests': 'Aucune demande',
    'approve': 'Approuver',
    'deny': 'Refuser',
    'approved': 'Approuvé',
    'denied': 'Refusé',
    'pending': 'En attente',
    'availableCourses': 'Cours disponibles',
    'markIncomplete': 'Marquer comme incomplet',
    'codeTypeHtml': 'HTML / CSS / JS',
    'codeTypeDart': 'Dart / Flutter',
    'preview': 'Aperçu',
    'noPreview': 'Pas de code à prévisualiser',
    'noContent': 'Pas de contenu pour cette leçon',
    'showingFallbackLang': 'Affiché dans une autre langue',
    'addCourse': 'Ajouter un cours',
    'editCourse': 'Modifier le cours',
    'addLesson': 'Ajouter une leçon',
    'editLesson': 'Modifier la leçon',
    'delete': 'Supprimer',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'edit': 'Modifier',
    'editUser': 'Modifier l\'utilisateur',
    'deleteUser': 'Supprimer l\'utilisateur',
    'deleteUserConfirm': 'Voulez-vous vraiment supprimer cet utilisateur ? Cette action est irréversible.',
    'cannotDeleteSelf': 'Vous ne pouvez pas supprimer votre propre compte',
    'userDeleted': 'Utilisateur supprimé',
    'title': 'Titre',
    'description': 'Description',
    'content': 'Contenu',
    'track': 'Filière',
    'price': 'Prix',
    'order': 'Ordre',
    'published': 'Publié',
    'videoUrl': 'URL vidéo (YouTube ou Drive)',
    'codeHtml': 'Code HTML/CSS/JS',
    'codeDart': 'Code Dart/Flutter',
    'hasExercise': 'A un exercice',
    'question': 'Question',
    'options': 'Options',
    'answerIndex': 'Index de la bonne réponse',
    'userRole': 'Rôle',
    'accessCourses': 'Cours activés',
    'student': 'Étudiant',
    'adminRole': 'Admin',
    'search': 'Rechercher...',
    'deleteConfirm': 'Êtes-vous sûr de vouloir supprimer?',
    'deleteWarning': 'Cette action est irréversible',
    'deleteLessonWarning': 'La leçon sera supprimée définitivement',
    'welcome': 'Bienvenue',
    'members': 'Étudiants',
    'openCourses': 'Cours ouverts',
    'statsCourses': 'Cours',
    'statsLessons': 'Leçons',
    'statsUsers': 'Utilisateurs',
    'lessonContent': 'Contenu de la leçon',
    'adminOnly': 'Espace admin',
    'switchToStudent': 'Retour à la vue étudiant',
    'users': 'Utilisateurs',
    'noAccess': 'Vous n\'avez pas accès à ce cours',
    'noAccessHint': 'Ceci est un cours payant, contactez l\'administration pour l\'activer',
    'contactAdmin': 'Contacter l\'administration',
    'adminContact': 'Pour activer le cours, envoyez un e-mail à l\'administration',
    'emailSent': 'Lien de réinitialisation envoyé à votre e-mail',
    'resetPassword': 'Réinitialiser le mot de passe',
    'sendResetLink': 'Envoyer le lien',
    'invalidEmail': 'E-mail invalide',
    'weakPassword': 'Mot de passe trop faible (6 caractères min)',
    'emailInUse': 'E-mail déjà utilisé',
    'userNotFound': 'Aucun compte avec cet e-mail',
    'wrongPassword': 'Mot de passe incorrect',
    'unknownError': 'Une erreur est survenue, réessayez',
    'passwordsDontMatch': 'Les mots de passe ne correspondent pas',
    'loginSuccess': 'Connecté avec succès',
    'registerSuccess': 'Compte créé avec succès',
    'loading': 'Chargement...',
    'retry': 'Réessayer',
    'error': 'Erreur',
    'success': 'Succès',
    'saved': 'Enregistré avec succès',
    'deleted': 'Supprimé avec succès',
    'notFound': 'Introuvable',
    'lessonProgress': 'Toutes les leçons de ce cours sont terminées!',
    'startCourse': 'Commencer le cours',
    'backToCourses': 'Retour aux cours',
    'exercisesSolved': 'Exercices résolus',
    'totalProgress': 'Progression globale',
    'learningTracks': 'Filières d\'apprentissage',
    'featuredCourses': 'Cours disponibles',
    'whyUs': 'Pourquoi Tamer Academy?',
    'whyUs1Title': 'Leçons pratiques',
    'whyUs1Desc': 'Apprenez avec le code et voyez le résultat instantanément',
    'whyUs2Title': 'Plusieurs niveaux',
    'whyUs2Desc': 'Contenu pour débutants et avancés',
    'whyUs3Title': '3 langues',
    'whyUs3Desc': 'Arabe, anglais et français',
    'joinToday': 'Rejoignez-nous et commencez votre parcours',
    'heroTitle': 'Libérez votre avenir dans la programmation',
    'heroSubtitle': 'Cours interactifs en développement web & mobile avec code en direct et résultats instantanés',
    'learnMore': 'En savoir plus',
    'privacy': 'Confidentialité',
    'terms': 'Conditions',
    'rights': 'Tous droits réservés',
    'codeNote': 'Astuce: modifiez le code puis rechargez pour voir le résultat',
    'runCode': 'Exécuter le code',
    'refreshResult': 'Actualiser le résultat',
    'fullscreen': 'Plein écran',
    'openInNewTab': 'Ouvrir dans un nouvel onglet',
    'dartpadNote': 'Cette leçon utilise DartPad — le chargement peut prendre un moment',
    'viewCode': 'Voir le code',
    'viewResult': 'Voir le résultat',
    'tabs': 'Sections',
    'videoNote': 'Lien vidéo: YouTube ou Drive',
    'homeSubtitle': 'Apprenez la programmation professionnellement — Web & Mobile',
    'webDevHeroTitle': 'Développement Web\nSimplifié',
    'webDevHeroSubtitle': 'HTML, CSS, JavaScript et frameworks modernes comme React',
    'mobileDevHeroTitle': 'Applications Mobiles\navec Flutter',
    'mobileDevHeroSubtitle': 'Créez des apps Android, iOS et web avec Dart',
    'trustedBy': 'Utilisé par les étudiants en',
    'featureShowcaseTitle': 'Une Expérience\nd\'Apprentissage Inégalée',
    'featureShowcaseSubtitle': 'Cours interactifs avec code en direct et résultats instantanés — apprenez en pratiquant',
    'feature1': 'Tutoriels vidéo de haute qualité',
    'feature2': 'Code interactif avec aperçu en direct',
    'feature3': 'Disponible sur mobile et web',
    'feature4': 'Exercices interactifs avec correction instantanée',
    'addTrack': 'Ajouter une filière',
    'editTrack': 'Modifier la filière',
    'noTracks': 'Aucune filière pour le moment',
    'tags': 'Mots-clés',
    'color': 'Couleur',
    'icon': 'Icône',
    'pickImage': 'Appuyez pour choisir une image',
    'draft': 'Brouillon',
    'image': 'Image',
    'imageUrlHint': 'Collez le lien de l\'image ici...',
    'pickFromGallery': 'Choisir dans la galerie',
    'pickFromCamera': 'Prendre une photo',
    'pickImageOrUrl': 'Choisissez une image ou entrez un lien',
    'invalidImageUrl': 'Lien d\'image invalide',
    'imagePickError': 'Erreur lors de la sélection de l\'image',
    'browseFiles': 'Parcourir les fichiers',
    'dragToResize': 'Glissez pour redimensionner — ou entrez les valeurs ci-dessous',
    'imageDimensions': 'Dimensions de l\'image',
    'reset': 'Réinitialiser',
    'width': 'Largeur',
    'height': 'Hauteur',
    'auto': 'Auto',
    'imageFit': 'Mode d\'ajustement',
    'fitCover': 'Couvrir (rogner)',
    'fitContain': 'Contenir (complet)',
    'fitFill': 'Étirer',
    'fitWidth': 'Ajuster à la largeur',
    'storagePermissionError': 'Permission Storage refusée — vérifiez les règles et le rôle admin',
    'imageUploadFailed': 'Échec d\'envoi de l\'image, sauvegarde avec l\'URL si fournie',
    'homework': 'Devoir',
    'homeworkHint': 'Écrivez votre code puis soumettez',
    'writeCodeHere': 'Écrire le code ici...',
    'submitHomework': 'Soumettre',
    'homeworkSent': 'Devoir soumis ✓',
    'homeworkPending': 'En attente',
    'homeworkReviewed': 'Corrigé',
    'homeworkEmptyError': 'Devoir vide interdit',
    'myHomeworks': 'Mes devoirs',
    'noHomeworks': 'Aucun devoir',
    'grade': 'Note',
    'feedback': 'Commentaire',
    'noFeedback': 'Pas de commentaire',
    'randomQuestion': 'Question aléatoire',
    'pickRandom': 'Choisir au hasard',
    'questionNumber': 'Question #',
    'allowRepeat': 'Autoriser répétition',
    'noRepeat': 'Sans répétition',
    'seenQuestions': 'Vues',
    'resetSeen': 'Réinitialiser',
    'allQuestionsSeen': 'Toutes vues ! Réinitialiser',
    'allQuestions': 'Toutes les questions',
    'importExcel': 'Importer Excel',
    'pasteQuick': 'Collage rapide',
    'need9Questions': '9 questions requises (3 langues)',
    'questionsCount': 'Nombre',
    'homeworkSubmissions': 'Soumissions',
    'noSubmissions': 'Aucune soumission',
    'review': 'Corriger',
    'reviewHomework': 'Corriger',
    'homeworkReviewSuccess': 'Corrigé',
    'pendingHomeworks': 'En attente',
    'reviewedHomeworks': 'Corrigés',
    'shuffleQuestions': 'Mélanger',
    'homeworkPrompt': 'Consigne',
    'hasHomework': 'A un devoir',
    'questions': 'Questions',
    'oralQuestions': 'Questions orales',
    'homeworkCode': 'Code devoir',
    'codeAnswer': 'Réponse code',
    'quickPasteTitle': 'Collage — une par ligne',
    'quickPasteHint': 'Collez questions',
    'quickPasteSolutionsHint': 'Collez solutions',
    'importHint': 'Excel: q_ar | s_ar | q_en | s_en | q_fr | s_fr',
    'homeworkProgress': 'Progression devoirs',
    'filterByCourse': 'Filtrer par cours',
    'filterByStatus': 'Filtrer par statut',
    'allStatus': 'Tous',
    'newHomeworksBadge': 'Nouveau',
  };

  static const _all = {
    'ar': _ar,
    'en': _en,
    'fr': _fr,
  };

  String get languageCode => locale.languageCode;

  bool get isRtl => languageCode == 'ar';

  String t(String key) {
    return _all[languageCode]?[key] ?? _en[key] ?? key;
  }

  static String of(BuildContext context) {
    final l10n = Localizations.of<AppLocalizations>(context, AppLocalizations);
    return l10n?.languageCode ?? 'ar';
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en', 'fr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant AppLocalizationsDelegate old) => false;
}